### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by amajidsinar** [nodefluxio/vortex#106]
I'm having problems during installation on branch `add-new-examples`

```
Step 6/27 : RUN apt-get update && apt-get install -y --no-install-recommends         curl         libglib2.0-0 libsm6 libxext6 libxrender-dev &&     apt-get autoremove -y &&     apt-get clean &&     rm -rf /root/.cache &&     rm -rf /var/lib/apt/lists/*
 ---> Running in e61d9eafe50e
OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=10.2, please update your driver to a newer version, or use an earlier cuda container\\\\n\\\"\"": unknown
```

Thanks a lot

**Comment by triwahyuu** [comment]
from the nvidia-docker [FAQ](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-fix-unsatisfied-condition-cuda--xy) I think the problem is that the installed driver on your machine is required to be higher. From the [nvidia release notes](https://docs.nvidia.com/cuda/archive/10.2/cuda-toolkit-release-notes/index.html#major-components__table-cuda-toolkit-driver-versions), cuda 10.2 required to use driver version >=440.33 
can you post the version of the nvidia driver by running `nvidia-smi`?
